(defun vhdl-set-prj-file ()
  (interactive)
  (setq files_prj (directory-files (lsp-workspace-root) nil "\\.prj$"))
  (if (= 0 (length files_prj))
      (message "No .prj files found")
    (if (> (length files_prj) 1)
        (message "More than one .prj files found. Needs to be imported manually")
      (vhdl-import-project (concat (lsp-workspace-root) "/" (nth 0 files_prj)))
      )
    )
  )
